axon:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29094,localhost:29096
    default-topic: Axon.Account.Events
    client-id: kafka-axon-account
    message-converter-mode: default # alternative is cloud_event <https://cloudevents.io/>
    properties:
      security.protocol: PLAINTEXT # PLAINTEXT for no security purpose
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: kafka-axon-account-txn
      retries: 5 # bigger than zero in case of using transactional confirmation-mode
      event-processor-mode: tracking
    consumer:
      event-processor-mode: pooled_streaming

  axonserver:
    enabled: false
  serializer:
    general: jackson
    events: jackson
    messages: jackson

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

server:
  port : 20261

spring:
  application:
    name: account

  # Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:16851/db_account
    username: itpusr
    password: itp@168
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
